---
# file: roles/common/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - libselinux-python

- name: disable ip*tables
  template: src={{item}}.j2 dest=/etc/sysconfig/{{item}} owner=root group=root mode=0600
  with_items:
    - iptables
    - ip6tables

- name: disable selinux
  selinux: state=disabled
  when: ansible_selinux.status is not defined or ansible_selinux.status != "disabled"

- name: reboot after change selinux
  shell: nohup bash -c "sleep 2s && reboot" &
  when: ansible_selinux.status is not defined or ansible_selinux.status != "disabled"

- name: wait for the server to go down (reboot)
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  when: ansible_selinux.status is not defined or ansible_selinux.status != "disabled"

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22
  when: ansible_selinux.status is not defined or ansible_selinux.status != "disabled"
